[[resources-project]]
== Project

List all project for given user credentials.

[[resources-project-list]]
=== Project List


A `GET` request is used to access the project list

operation::project-list[snippets='curl-request,http-request,request-headers']


[[resources-project-get-one]]
=== Get a single Project

Get single project object.

operation::project-get-one[snippets='curl-request,http-request,path-parameters,request-headers,http-response']


[[resources-project-post]]
=== Create a new Project

`POST` request to generate new Project object.

operation::project-post[snippets='curl-request,http-request,request-fields,request-headers,http-response']

[[resources-project-put]]
=== Update a exsiting Project

`PUT` request to update existing Project object.

operation::project-put[snippets='curl-request,http-request,request-fields,request-headers,http-response']

[[resources-project-delete-one]]
=== Delete a single Project

Delete single project object.

operation::project-delete-one[snippets='curl-request,http-request,path-parameters,request-headers,http-response']